issuer = "HCL"

Invoice_Number = r'Invoice No.*\n(.*)|Invoice Number\:(\d*)'
Invoice Date   = r'Invoice Date\:\n?(.*)'
Invoice Currency = r'Amount\((\w*)'
Invoice Description = r'Amount\(.*\)\n.\n(.*)|Amount\(.*\)\n(.*)'
Amount before Tax = r'Amount\(.*\)\n.*\n(\d+.*)|(\d+.*)\nOutput Tax'
Amount of Tax = r'Output Tax\s?\n(.*)'
Amount after Tax = r'Total Amount in\s?\(?.*\)?\n?(.*)'
PO Number = r'PO Number.*(.*)|PO No.*\n?(.*)'
Buyer Name = r'BILL TO PARTY.*\n(.*)|To\n(.*)'
Buyer Tax code =  r'VAT No\s?\:(.*)'
Seller Name = r'REGISTERED\s?\n?OFFICE\s?.?\n?(.*)'
Seller Tax code = r'VAT NO\s?\:(.*)'